"use client";
import store from "@/redux/store";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Provider } from "react-redux";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <Head>
          <title>RoboMart Bd - Online robotics shop Bangladesh</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
}
